Xiaomi Redmi 6 (cereus) port
jerinphilip/pmaports pull request #1
Opened 2023-09-17 14:58 UTC by jerinphilip

2023-09-17 19:54 UTC, hexaheximal requested changes

2023-09-17 19:54 UTC, hexaheximal commented on .ci/cereus-configure.sh
seems a bit too hardcoded but should be fine for now

2023-09-17 19:54 UTC, hexaheximal commented on .ci/xiaomi-cereus.prompt
why wHy WHY

this is so cursed

2023-09-19 18:05 UTC, jerinphilip commented
Moved to https://gitlab.com/postmarketOS/pmaports/-/merge_requests/4408

2023-09-20 15:15 UTC, closed without merging